# This yaml pipeline will deploy Application Insights
trigger: none

name: Create Application Insights
workspace:
  clean: all

pool:
  vmImage: "windows-2019"

parameters:
  - name: azureSubscription
    type: string
    displayName: Service Connection Name (Azure)
    default: amitabhdas-azure
  - name: resourceGroupName
    type: string
    displayName: Resource Group Name for the AppInsights
    default: RGCloud
  - name: appInsightsName
    type: string
    displayName: application Insights name
    default: mydemoappinsight
  - name: location
    type: string
    displayName: location for AppInsights
    default: EastUS2
  - name: appInsightsType
    type: string
    displayName: App Insights Type (ex- web,java,other)
    default: web
  - name: tags
    type: string
    displayName: Provide the resource tagging
    values:
      - env:test

steps:
- task: AzurePowerShell@5
  displayName: create - ApplicationInsights
  condition: succeeded()
  inputs:
    azureSubscription: ${{parameters.azureSubscription }}
    ScriptType: 'FilePath'
    ScriptPath: CoreInfra/ApplicationInsights/Scripts/Create-AppInsights.ps1
    ScriptArguments:  -ResourceGroupName ${{parameters.resourceGroupName }}
             -AppInsightsName '${{parameters.appInsightsName }}'
             -Location '${{parameters.location }}'
             -AppInsightsType '${{parameters.appInsightsType }}'
             -Tags '${{parameters.tags }}'
    azurePowerShellVersion: 'LatestVersion'